; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ESP-CODE-S/src
lib_dir = ESP-CODE-S/lib
include_dir = ESP-CODE-S/include
test_dir = ESP-CODE-S/test
data_dir = ESP-CODE-S/data
workspace_dir = ESP-CODE-S/.pio

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv
build_unflags = -std=gnu++11
build_flags = 
	-std=gnu++14
	-D VTABLES_IN_DRAM
	-I ESP-CODE-S/include
	-I ESP-CODE-S/include/Core
	-I ESP-CODE-S/include/Core/Async
	-I ESP-CODE-S/include/Core/Error
	-I ESP-CODE-S/include/Network
	-I ESP-CODE-S/include/Network/WiFi
	-I ESP-CODE-S/include/Network/HTTP
	-I ESP-CODE-S/include/Timer
	-I ESP-CODE-S/include/Utilities
	-I ESP-CODE-S/include/Events
	-I ESP-CODE-S/include/Optimization
	-I C:/Users/KAVEH/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src
	-I C:/Users/KAVEH/.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src
	-I C:/Users/KAVEH/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps = 
	heman/AsyncMqttClient-esphome@^2.1.0
	WiFi
	WiFiClientSecure
	HTTPClient
	gilmaimon/ArduinoWebsockets@^0.5.3
	bblanchon/ArduinoJson@^6.21.3
	esphome/AsyncTCP-esphome@^2.0.0
lib_ignore = ESPAsyncTCP
